name: pystrometry-environment
channels:
  - conda-forge
dependencies:
  - python == 3.9
  - numpy == 1.24.3
  - pip == 23.1.2
  - kepmodel == 1.0.6
  - pandas == 2.0.2
  - matplotlib == 3.7.1
  - astroquery == 0.4.6
  - astropy == 5.0.6
  - sympy
  - scipy
  - pip:
    - linearfit
