name: pystrometry-environment-3p10
channels:
  - conda-forge
dependencies:
  - python == 3.10
  - numpy
  - pip
  - kepmodel
  - pandas
  - pyarrow
  - matplotlib
  - astroquery
  - astropy
  - sympy
  - scipy
  - uncertainties
  - pip:
    - linearfit
