name: Python Package Tests with Python 3.10 and Mambaforge

on: [push, pull_request]

jobs:
  test-python-3p10:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v4

    - name: Set up Mambaforge with Python 3.10
      uses: conda-incubator/setup-miniconda@v2
      with:
        miniforge-variant: Mambaforge
        python-version: 3.10
        use-mamba: true
        auto-activate-base: false

    - name: Create env from file
      shell: bash -l {0}
      run: |
        mamba env create -f environment-3p10.yml
        source activate pystrometry-environment-3p10

    - name: Install pytest
      shell: bash -l {0}
      run: |
        mamba install pytest

    - name: Run tests
      shell: bash -l {0}
      run: |
        pytest pystrometry/tests
        pytest pystrometry/utils/tests