name: Python Package using Conda

on: [push]

jobs:
  build-linux-python-3p10:
      runs-on: ubuntu-latest
      strategy:
        max-parallel: 5

      steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'
      - name: Install Mamba
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          pip install mamba
      - name: Install dependencies
        run: |
          mamba env create --file environment-3.10.yml --name pystrometry-env-3p10
          source activate pystrometry-env-3p10
      - name: Lint with flake8
        run: |
          mamba install flake8
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
        continue-on-error: true
      - name: Test with pytest
        run: |
          mamba install pytest
          pytest pystrometry/tests
          pytest pystrometry/utils/tests


  